version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - mlflow